source 'https://rubygems.org'

gem 'rails', '~> 6.1.0'
gem 'bootsnap', require: false
gem 'whenever', require: false
gem 'sequel'
gem 'honeybadger', '~> 4.0'
gem 'paper_trail'
gem 'psych'
gem 'pluck_to_hash'
gem 'textacular'
gem 'fast_jsonapi'
gem 'oj'
gem 'json'
gem 'render_async'
gem 'config'
gem 'stripe'
gem 'validate_url'
gem 'view_source_map'
gem 'pretender'
gem 'rubycritic', require: false, groups: [:development, :test]
gem 'sentry-ruby'
gem 'sentry-rails'
gem 'sentry-sidekiq'
gem 'active_model_serializers', '~> 0.10.0'
gem 'acts_as_list'
gem 'ahoy_email'
gem 'annotate'
gem 'ros-apartment', require: 'apartment'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.42'
gem 'brakeman'
gem 'browser'
gem 'view_component'
gem 'capistrano-rails-console', require: false
gem 'capistrano-sidekiq', group: :development
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'country_select', '~> 3.1'
gem 'devise'
gem 'exception_notification'
gem 'gon'
gem 'inherited_resources'
gem 'marginalia'
gem 'mini_magick'
gem 'momentjs-rails', '>= 2.9.0'
gem 'nested_form'
gem 'nokogiri'
gem 'roo'
gem 'ruby-progressbar'
gem 'simple_form'
gem 'slim'
gem 'slim-rails'
gem 'slim_lint'
gem 'webpacker'
gem 'webpacker-react'
gem 'wicked'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'email_validator'
gem 'google-api-client', '~> 0.11', require: 'google/apis/calendar_v3'
gem 'rubyzip'
gem 'searchkick'
gem 'faraday_middleware-aws-sigv4'
gem 'rqrcode'
gem 'x-editable-rails'
gem 'slack-notifier'
gem 'premailer-rails'
gem 'rubocop'
gem 'lograge'
gem 'coffee-rails', '~> 5.0.0'
gem 'faker', '~> 1.8.4'
gem 'jbuilder', '~> 2.5'
gem 'pg', '~> 1.2.3'
gem 'puma', '< 6'
gem 'puma-status', require: false
gem 'rack-mini-profiler', require: false
gem 'sassc-rails'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'
# Use Redis adapter to run Action Cable in production
gem 'redis', '4.5.0'
gem 'sidekiq', '5.2.1'
gem 'sidekiq-status'
gem 'sidekiq-limit_fetch'
gem 'kaminari'
gem 'countries'
gem 'storext'
# gem 'newrelic_rpm'
gem 'skylight'
gem 'active_decorator'
gem 'ahoy_matey'
gem 'file_validators' # limit uploaded file size
gem 'activerecord-import'
gem 'httparty'
gem 'savon'
gem 'graphql', '1.9.6'
gem 'pandadoc-api'
gem 'ox' # xml parsing
gem 'twilio-ruby'
gem 'fog-aws'
gem 'asset_sync'
gem 'graphiql-rails', group: :development
gem 'social-share-button'
gem 'jwt'
gem 'grover'
gem 'active_model_otp'
gem 'carrierwave-base64'
gem 'dentaku'
gem 'amoeba'
gem 'htmltoword', '1.1.0'
gem 'charlock_holmes'
gem "uk_postcode", "~> 2.1.0"
gem 'esendex'
gem 'faraday'
gem 'net-ssh'
gem 'net-scp'
gem 'mixpanel-ruby'
gem 'combine_pdf'
gem 'pagy'
gem 'caxlsx'
gem 'caxlsx_rails'
gem 'rack-attack'
# Use Capistrano for deployment
group :development do
  gem 'capistrano', '~> 3.6'
  gem 'capistrano-bundler'
  gem 'capistrano-npm'
  gem 'capistrano-passenger'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-yarn'
  gem 'rbnacl', '~> 7.0'
  gem 'bcrypt_pbkdf', '1.0.1'
  gem 'bullet'
  gem 'listen', '~> 3.3.0'
  gem 'ruby-growl'
  gem 'spring'
  gem 'web-console'
  gem 'xmpp4r'
  gem "letter_opener"
  gem 'solargraph'
end

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'pry'
  gem 'pry-nav'
  gem 'rb-readline'
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 5.0.0'
  gem 'capybara'
  gem 'rspec_junit_formatter'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  # gem 'guard-rspec'
  gem 'dotenv-rails'
  gem 'execution_time'
end

group :test do
  gem 'shoulda-matchers', '~> 4.0', require: false
  gem 'rspec-retry'
  gem 'rspec-longrun'
  gem 'simplecov', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
