version: 2.1
jobs:
  build:
    docker:
      - image: quay.io/buildah/stable:v1.27.0
    resource_class: ninhlv-9984/testklass
    steps:
      - checkout
      - run:
          name: sanity-test
          command: |
            buildah version
      - run:
          name: Building-a-container
          command: |
            buildah bud -f Dockerfile -t applicaa:latest .
workflows:
  build-workflow:
    jobs:
      - build
