version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.5
    resource_class: ninhlv-9984/testklass
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}-{{ .Runner.OS }}-{{ .Revision }}
          paths:
            - vendor/bundle
      - run:
          name: Install Dependencies
          command: |
            gem install bundler:2.2.16
            bundle install --jobs=4 --retry=3 --path=vendor/bundle
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}-{{ .Runner.OS }}-{{ .Revision }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/app
          paths:
            - vendor/bundle
workflows:
  build-workflow:
    jobs:
      - build
