version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: ninhlv-9984/testklass
    steps:
      - checkout
      - run: echo "Buiding the docker image"
      - run:  docker build -f Dockerfile -t applicaa:latest .
workflows:
  build-workflow:
    jobs:
      - build
