version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: ninhlv-9984/testklass
    steps:
      - checkout
      - run: echo "Buiding the docker image"
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:  docker build -f Dockerfile -t applicaa:latest .
workflows:
  build-workflow:
    jobs:
      - build
